FROM node:9-alpine
RUN rm -rf /var/cache/apk/* && \
    mkdir /app
WORKDIR /app

RUN apk update && \
    apk upgrade && \
    apk --update add python py-pip git make g++ && \
    apk add --no-cache bash && \
    npm install --unsafe-perm -g truffle@5.0.0-beta.2 && \
    npm install -g mocha@5.2.0 && \
    npm install -g mocha-junit-reporter@1.18.0

COPY . /app/

CMD truffle test ./test/BitcoinPrice.test.js --network development

